RUN 
    addgroup testssl && \
    # --gecos account's purpose 
    # sudo usermod -aG docker $USER
    adduser --group  testssl docker sudo --gecous "testssl user"  --shell /bin/bash --disabled-passord testssl && \
    ln -s /home/testssl/testssl.sh /usr/local/bin/ && \
    mkdir -m 755 -p /home/testssl/etc /home/testssl/bin

USER testssl
WORKDIR /home/testssl/

COPY --chown=testssl:testssl etc/. /home/testssl/etc/
COPY --chown=testssl:testssl bin/. /home/testssl/bin/
COPY --chown=testssl:testssl testssl.sh  /home/testssl/
# COPY --chown=testssl:testssl . /home/testssl/

ENTRYPOINT ["testssl.sh"]

CMD ["--help"]