name: docker

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]


env:
  BUILD_VERSION: "3.2"

jobs:
    deploy:
        runs-on: ubuntu-22.04

        steps:
            - name: Source checkout
              uses: actions/checkout@v4
            - name: Setup Buildx
              id: buildx
              uses: docker/setup-buildx-action@v3
            
            - name: github docker login
              if: ${{ github.event_name != 'pull_request'}}
              uses: docker/login-action@v3.3.0
              with:
                registry: ghcr.io
                username: ${{ github.actor}}
                password: ${{ secrets.GITHUB_TOKEN}}
            - name: Build and push
              uses: docker/build-push-action@v6.15.0
              with:
                push: ${{ github.event_name != 'pull_request' }}
                context: .
                file: Dockerfile.git
                build-args: BUILD_VERSION
                cache-from: type=gha, scope=${{ github.workflow }}
                tags: |
                    ghcr.io/${{ github.repository }}:${{ env.BUILD_VERSION }}
                    ghcr.io/${{ github.repository }}:latest